"""empty message

Revision ID: 15849d84e5c2
Revises: c53a070876f1
Create Date: 2019-12-11 21:51:09.078932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15849d84e5c2'
down_revision = 'c53a070876f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
